CREATE DATABASE Loja_Eletronicos;
USE Loja_Eletronicos;

CREATE TABLE CLIENTE(
    ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT ,
    NOME VARCHAR(100)  ,
    CPF CHAR(11),
    TELEFONE VARCHAR(28)
);

CREATE TABLE PRODUTO(
ID_PRODUTO INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(50),
PRECO DECIMAL(10,2),
CATEGORIA VARCHAR(40),
MARCA VARCHAR(10)
);

CREATE TABLE VENDA(
ID_VENDA INT PRIMARY KEY AUTO_INCREMENT,
DATAS DATE,
VALOR_TOTAL DECIMAL(10,2) NOT NULL ,
ID_CLIENTE INT ,
FOREIGN KEY (ID_CLIENTE) REFERENCES ID_CLIENTE
);

CREATE TABLE ITEM_VENDA(
ID_ITEM_VENDA INT PRIMARY KEY AUTO_INCREMENT,
ID_VENDA INT,
ID_PRODUTO INT,
QUANTIDADE INT,
PRECO_UNITARIO DECIMAL(10,2),
PRIMARY KEY (ID_VENDA,ID_PRODUTO),
FOREIGN KEY (ID_VENDA) REFERENCES ID_VENDA,
FOREIGN KEY(ID_PRODUTO) REFERENCES ID_PRODUTO
);

CREATE TABLE PAGAMENTO(
ID_PAGAMENTO INT PRIMARY KEY AUTO_INCREMENT,
ID_VENDA INT,
TIPO_PAGAMENTO VARCHAR(50),
VALOR_PAGAMENTO DECIMAL(10,2),
FOREIGN KEY (ID_VENDA) REFERENCES ID_VENDA
);

CREATE TABLE ESTOQUE(
ID_PRODUTO INT PRIMARY KEY,
QUANTIDADE INT ,
FOREIGN KEY (ID_PRODUTO) REFERENCES ID_PRODUTO
);